#!/bin/bash


for SIZE in 128
do

# Calculate number of files

if [ $SIZE -eq 128 ]
then
	_fileSize=32
else
	_fileSize=64
fi

_nrFiles=$[$SIZE/$_fileSize]

# Write throughput

	hadoop jar $HADOOP_HOME/hadoop-test.jar \
	TestDFSIO \
	-write \
	-nrFiles $_nrFiles \
	-fileSize $_fileSize &> /dev/null

# Read throughput

	hadoop jar $HADOOP_HOME/hadoop-test.jar \
	TestDFSIO \
	-read \
	-nrFiles $_nrFiles \
	-fileSize $_fileSize &> /dev/null

done
